# docker-compose
# author: dreamlu
# github.com/dreamlu
version: '3'
services:
  #nginx:
  #  container_name: d-nginx
  #  image: nginx
  #  restart: always
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - ./nginx/conf.d:/etc/nginx/conf.d

  # mysql-server
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: 5.7
        # 账号密码同下环境变量值
        MYSQL_DATABASE: deercoder-gin
        MYSQL_USER: dreamlu
        MYSQL_PASSWORD: dreamlu
        MYSQL_ROOT_PASSWORD: dreamlu
    #command:
    #privileged: true
    container_name: d-mysql
    #image: mysql/mysql-server:5.7
    #image: mysql:5.7
    environment:
      MYSQL_DATABASE: deercoder-gin
      MYSQL_USER: dreamlu
      MYSQL_PASSWORD: dreamlu
      MYSQL_ROOT_PASSWORD: dreamlu
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    ports:
      - 3308:3306
    restart: always
    # sql备份目录
    volumes:
      - /home/ubuntu/dreamlu/bak:/bak
  # redis
#  redis:
#    image: redis:4.0
#    ports:
#      - 6378:6379
#    container_name: d-redis
#    restart: always
  # api gateway
  demo:
    image: registry.cn-hangzhou.aliyuncs.com/dreamlu/common:deercoder-gin-demo
    ports:
      - 9000:9000
    container_name: d-demo
    restart: always
    #depends_on:
    #  - mysql