name: Build and Release apk

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
#    - run: cd txgc-app
    - run: cd txgc-app && flutter pub get && flutter build apk
    - name: Upload APK
    - run: curl -F 'file="txgc-app/build/app/outputs/flutter-apk/app-release.apk"' -F '_api_key=${{secrets.PGYER_API_KEY}}' https://www.pgyer.com/apiv2/app/upload

