name: Build and Release apk

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
    - name: Upload APK
      run: |
        pwd
        wget https://github.com/dreamlu/play/releases/download/apk/app-release.apk
        ls
        curl -F 'file=@app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' -X POST https://www.pgyer.com/apiv2/app/upload

