name: Build and Release apk

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
    - name: Upload APK
    - run: pwd
    - run: ls
    - run: curl -LJO https://github.com/wobangkj/txgc-app/releases/download/v1.1.5/app-release.apk
    - run: curl -F 'file="app-release.apk"' -F '_api_key=${{ secrets.PGYER_API_KEY }}' -X POST https://www.pgyer.com/apiv2/app/upload

